deploy-kubernetes:
  needs: build-and-push
  runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    - name: Deploy Kubernetes
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          rm -rf devops-kubernet-deploy
          git clone https://github.com/SantRhay/devops-kubernet-deploy.git
          cd devops-kubernet-deploy

          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
