name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USER }}/devops-web:latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME -f docker/Dockerfile .

      - name: Push Docker Image
        run: docker push $IMAGE_NAME


  deploy-kubernetes:

    needs: build-and-push
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Deploy Kubernetes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! -d "devops-kubernetes-deploy" ]; then
              git clone https://github.com/SantRhay/devops-kubernet-deploy.git
            else
              cd devops-kubernetes-deploy
              git pull
              cd ..
             fi

             cd devops-kubernetes-deploy

             kubectl apply -f k8s/deployment.yaml
             kubectl apply -f k8s/service.yaml
