name: Kubernetes Validate

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Validar deployment
        run: kubectl apply --dry-run=client --validate=false -f deployment.yaml

      - name: Validar service
        run: kubectl apply --dry-run=client --vallsidate=false -f service.yaml